[package]
name = "QuantumRandom"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
description = "This is the rust implementation of the ANU Quantum Random Number System. You can easily generate an arbitrary number of u8's, u16's, u32's, u64's, and u128's"
license = "GNU GPL 3.0"
license-file = "LICENSE"
# For deployment on crates.io
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
reqwest = "0.9.10"
rand = "0.6.5"
atoi = "0.3.1"